version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - http/realm-ui

formatters:
  enable:
    - gofmt
