# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RealmAT0020 < Formula
  desc "Inheritable and overridable configuration management "
  homepage "https://github.com/steviebps/realm"
  version "0.0.20-pre.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20-pre.0/realm_0.0.20-pre.0_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "114a8da1a0e9ea2c06b539c09931c15357b324783231cc1601adc86dde38d013"

      def install
        bin.install "realm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20-pre.0/realm_0.0.20-pre.0_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1e2dfb03c36a40194d712e5b0b07c6efed7d06adbecf6e3dab778756bed02613"

      def install
        bin.install "realm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20-pre.0/realm_0.0.20-pre.0_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "cd325300dcd43ece07d581d52cb7cf431b120bf54d1d82f44f45f0980e71b722"

      def install
        bin.install "realm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steviebps/realm/releases/download/v0.0.20-pre.0/realm_0.0.20-pre.0_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b375270dcfa661573350a891f3b89c677d06c1b73961ed11141f4a584a6aa96a"

      def install
        bin.install "realm"
      end
    end
  end
end
